services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/storage
      - /app/bootstrap/cache
      - node_modules:/app/laravel/node_modules
    working_dir: /app/laravel
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db
      - mailpit
      - node
    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kursdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP-Port
  node:
    image: node:latest
    working_dir: /app/laravel
    ports:
      - "5173:5173"  # Vite dev server
      - "5174:5174"  # Vite dev server
      - "5175:5175"  # Vite dev server
      - "5176:5176"  # Vite dev server
    volumes:
      - .:/app
      - node_modules:/app/laravel/node_modules
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
volumes:
    db_data:
    node_modules:
